[('C', 'Major'), ('C sharp', 'Major'), [0, 5], 2]
[('C sharp', 'Major'), ('G', 'Major'), [0, 6], 2]
[('G', 'Major'), ('C sharp', 'Major'), [0, 6], 2]
[('C sharp', 'Major'), ('C', 'Major'), [0, 5], 2]
[('C', 'Major'), ('B', 'Major'), [11, 4], 2]
[('B', 'Major'), ('B flat', 'Major'), [10, 3], 2]
[('B flat', 'Major'), ('A', 'Major'), [9, 2], 2]
[('B flat', 'Major'), ('B', 'Major'), [10, 3], 2]
[('B flat', 'Major'), ('E', 'Major'), [9, 3], 2]
[('B flat', 'Major'), ('F sharp', 'Major'), [10, 3, 5], 3]
[('B flat', 'Major'), ('D', 'Major'), [9, 2, 7], 3]
[('B flat', 'Major'), ('C sharp', 'Major'), [0, 10, 3, 5], 4]
[('B flat', 'Major'), ('G', 'Major'), [0, 9, 2, 7], 4]
[('B flat', 'Major'), ('G sharp', 'Major'), [0, 10, 3, 5, 7], 5]
[('B flat', 'Major'), ('C', 'Major'), [0, 9, 2, 5, 7], 5]
[('B flat', 'Major'), ('E flat', 'Major'), [0, 2, 3, 5, 7, 10], 6]
[('B flat', 'Major'), ('F', 'Major'), [0, 2, 5, 7, 9, 10], 6]
[('B', 'Major'), ('C', 'Major'), [11, 4], 2]
[('C', 'Major'), ('F sharp', 'Major'), [11, 5], 2]
[('C', 'Major'), ('G sharp', 'Major'), [0, 5, 7], 3]
[('C', 'Major'), ('E', 'Major'), [9, 11, 4], 3]
[('C', 'Major'), ('A', 'Major'), [9, 2, 11, 4], 4]
[('C', 'Major'), ('E flat', 'Major'), [0, 2, 5, 7], 4]
[('C', 'Major'), ('B flat', 'Major'), [0, 9, 2, 5, 7], 5]
[('C', 'Major'), ('D', 'Major'), [9, 2, 11, 4, 7], 5]
[('C', 'Major'), ('G', 'Major'), [0, 2, 4, 7, 9, 11], 6]
[('C', 'Major'), ('F', 'Major'), [0, 2, 4, 5, 7, 9], 6]
[('B', 'Major'), ('F', 'Major'), [10, 4], 2]
[('F', 'Major'), ('B', 'Major'), [10, 4], 2]
[('F', 'Major'), ('F sharp', 'Major'), [10, 5], 2]
[('F', 'Major'), ('E', 'Major'), [9, 4], 2]
[('F', 'Major'), ('A', 'Major'), [9, 2, 4], 3]
[('F', 'Major'), ('C sharp', 'Major'), [0, 10, 5], 3]
[('F', 'Major'), ('G sharp', 'Major'), [0, 10, 5, 7], 4]
[('F', 'Major'), ('D', 'Major'), [9, 2, 4, 7], 4]
[('F', 'Major'), ('G', 'Major'), [0, 9, 2, 4, 7], 5]
[('F', 'Major'), ('E flat', 'Major'), [0, 2, 10, 5, 7], 5]
[('F', 'Major'), ('B flat', 'Major'), [0, 2, 5, 7, 9, 10], 6]
[('F', 'Major'), ('C', 'Major'), [0, 2, 4, 5, 7, 9], 6]
[('B', 'Major'), ('G', 'Major'), [11, 4, 6], 3]
[('G', 'Major'), ('G sharp', 'Major'), [0, 7], 2]
[('G', 'Major'), ('F sharp', 'Major'), [11, 6], 2]
[('G', 'Major'), ('B', 'Major'), [11, 4, 6], 3]
[('G', 'Major'), ('E flat', 'Major'), [0, 2, 7], 3]
[('G', 'Major'), ('B flat', 'Major'), [0, 9, 2, 7], 4]
[('G', 'Major'), ('E', 'Major'), [9, 11, 4, 6], 4]
[('G', 'Major'), ('A', 'Major'), [9, 2, 11, 4, 6], 5]
[('G', 'Major'), ('F', 'Major'), [0, 9, 2, 4, 7], 5]
[('G', 'Major'), ('C', 'Major'), [0, 2, 4, 7, 9, 11], 6]
[('G', 'Major'), ('D', 'Major'), [2, 4, 6, 7, 9, 11], 6]
[('B', 'Major'), ('E flat', 'Major'), [8, 10, 3], 3]
[('E flat', 'Major'), ('A', 'Major'), [8, 2], 2]
[('E flat', 'Major'), ('E', 'Major'), [8, 3], 2]
[('E flat', 'Major'), ('D', 'Major'), [2, 7], 2]
[('E flat', 'Major'), ('B', 'Major'), [8, 10, 3], 3]
[('E flat', 'Major'), ('G', 'Major'), [0, 2, 7], 3]
[('E flat', 'Major'), ('F sharp', 'Major'), [8, 10, 3, 5], 4]
[('E flat', 'Major'), ('C', 'Major'), [0, 2, 5, 7], 4]
[('E flat', 'Major'), ('C sharp', 'Major'), [0, 8, 10, 3, 5], 5]
[('E flat', 'Major'), ('F', 'Major'), [0, 2, 10, 5, 7], 5]
[('E flat', 'Major'), ('B flat', 'Major'), [0, 2, 3, 5, 7, 10], 6]
[('E flat', 'Major'), ('G sharp', 'Major'), [0, 3, 5, 7, 8, 10], 6]
[('B', 'Major'), ('G sharp', 'Major'), [8, 1, 10, 3], 4]
[('G sharp', 'Major'), ('A', 'Major'), [8, 1], 2]
[('G sharp', 'Major'), ('G', 'Major'), [0, 7], 2]
[('G sharp', 'Major'), ('D', 'Major'), [1, 7], 2]
[('G sharp', 'Major'), ('C', 'Major'), [0, 5, 7], 3]
[('G sharp', 'Major'), ('E', 'Major'), [8, 1, 3], 3]
[('G sharp', 'Major'), ('B', 'Major'), [8, 1, 10, 3], 4]
[('G sharp', 'Major'), ('F', 'Major'), [0, 10, 5, 7], 4]
[('G sharp', 'Major'), ('B flat', 'Major'), [0, 10, 3, 5, 7], 5]
[('G sharp', 'Major'), ('F sharp', 'Major'), [8, 1, 10, 3, 5], 5]
[('G sharp', 'Major'), ('C sharp', 'Major'), [0, 1, 3, 5, 8, 10], 6]
[('G sharp', 'Major'), ('E flat', 'Major'), [0, 3, 5, 7, 8, 10], 6]
[('B', 'Major'), ('D', 'Major'), [1, 11, 4, 6], 4]
[('D', 'Major'), ('C sharp', 'Major'), [1, 6], 2]
[('D', 'Major'), ('G sharp', 'Major'), [1, 7], 2]
[('D', 'Major'), ('E flat', 'Major'), [2, 7], 2]
[('D', 'Major'), ('B flat', 'Major'), [9, 2, 7], 3]
[('D', 'Major'), ('F sharp', 'Major'), [1, 11, 6], 3]
[('D', 'Major'), ('B', 'Major'), [1, 11, 4, 6], 4]
[('D', 'Major'), ('F', 'Major'), [9, 2, 4, 7], 4]
[('D', 'Major'), ('C', 'Major'), [9, 2, 11, 4, 7], 5]
[('D', 'Major'), ('E', 'Major'), [1, 11, 4, 6, 9], 5]
[('D', 'Major'), ('A', 'Major'), [1, 2, 4, 6, 9, 11], 6]
[('D', 'Major'), ('G', 'Major'), [2, 4, 6, 7, 9, 11], 6]
[('B', 'Major'), ('A', 'Major'), [8, 1, 11, 4, 6], 5]
[('A', 'Major'), ('B flat', 'Major'), [9, 2], 2]
[('A', 'Major'), ('G sharp', 'Major'), [8, 1], 2]
[('A', 'Major'), ('E flat', 'Major'), [8, 2], 2]
[('A', 'Major'), ('C sharp', 'Major'), [8, 1, 6], 3]
[('A', 'Major'), ('F', 'Major'), [9, 2, 4], 3]
[('A', 'Major'), ('F sharp', 'Major'), [8, 1, 11, 6], 4]
[('A', 'Major'), ('C', 'Major'), [9, 2, 11, 4], 4]
[('A', 'Major'), ('B', 'Major'), [8, 1, 11, 4, 6], 5]
[('A', 'Major'), ('G', 'Major'), [9, 2, 11, 4, 6], 5]
[('A', 'Major'), ('E', 'Major'), [1, 4, 6, 8, 9, 11], 6]
[('A', 'Major'), ('D', 'Major'), [1, 2, 4, 6, 9, 11], 6]
[('B', 'Major'), ('C sharp', 'Major'), [8, 1, 10, 3, 6], 5]
[('C sharp', 'Major'), ('D', 'Major'), [1, 6], 2]
[('C sharp', 'Major'), ('A', 'Major'), [8, 1, 6], 3]
[('C sharp', 'Major'), ('F', 'Major'), [0, 10, 5], 3]
[('C sharp', 'Major'), ('B flat', 'Major'), [0, 10, 3, 5], 4]
[('C sharp', 'Major'), ('E', 'Major'), [8, 1, 3, 6], 4]
[('C sharp', 'Major'), ('B', 'Major'), [8, 1, 10, 3, 6], 5]
[('C sharp', 'Major'), ('E flat', 'Major'), [0, 8, 10, 3, 5], 5]
[('C sharp', 'Major'), ('G sharp', 'Major'), [0, 1, 3, 5, 8, 10], 6]
[('C sharp', 'Major'), ('F sharp', 'Major'), [1, 3, 5, 6, 8, 10], 6]
[('B', 'Major'), ('F sharp', 'Major'), [1, 3, 6, 8, 10, 11], 6]
[('F sharp', 'Major'), ('G', 'Major'), [11, 6], 2]
[('F sharp', 'Major'), ('C', 'Major'), [11, 5], 2]
[('F sharp', 'Major'), ('F', 'Major'), [10, 5], 2]
[('F sharp', 'Major'), ('B flat', 'Major'), [10, 3, 5], 3]
[('F sharp', 'Major'), ('D', 'Major'), [1, 11, 6], 3]
[('F sharp', 'Major'), ('A', 'Major'), [8, 1, 11, 6], 4]
[('F sharp', 'Major'), ('E flat', 'Major'), [8, 10, 3, 5], 4]
[('F sharp', 'Major'), ('G sharp', 'Major'), [8, 1, 10, 3, 5], 5]
[('F sharp', 'Major'), ('E', 'Major'), [8, 1, 3, 6, 11], 5]
[('F sharp', 'Major'), ('C sharp', 'Major'), [1, 3, 5, 6, 8, 10], 6]
[('F sharp', 'Major'), ('B', 'Major'), [1, 3, 6, 8, 10, 11], 6]
[('B', 'Major'), ('E', 'Major'), [1, 3, 4, 6, 8, 11], 6]
[('E', 'Major'), ('B flat', 'Major'), [9, 3], 2]
[('E', 'Major'), ('E flat', 'Major'), [8, 3], 2]
[('E', 'Major'), ('F', 'Major'), [9, 4], 2]
[('E', 'Major'), ('G sharp', 'Major'), [8, 1, 3], 3]
[('E', 'Major'), ('C', 'Major'), [9, 11, 4], 3]
[('E', 'Major'), ('C sharp', 'Major'), [8, 1, 3, 6], 4]
[('E', 'Major'), ('G', 'Major'), [9, 11, 4, 6], 4]
[('E', 'Major'), ('F sharp', 'Major'), [8, 1, 3, 6, 11], 5]
[('E', 'Major'), ('D', 'Major'), [1, 11, 4, 6, 9], 5]
[('E', 'Major'), ('A', 'Major'), [1, 4, 6, 8, 9, 11], 6]
[('E', 'Major'), ('B', 'Major'), [1, 3, 4, 6, 8, 11], 6]
[('C', 'Major'), ('C sharp', 'Major'), [0, 5], 2]
[('C sharp', 'Major'), ('G', 'Major'), [0, 6], 2]
[('G', 'Major'), ('C sharp', 'Major'), [0, 6], 2]
[('C sharp', 'Major'), ('C', 'Major'), [0, 5], 2]
[('C', 'Major'), ('B', 'Major'), [11, 4], 2]
[('B', 'Major'), ('B flat', 'Major'), [10, 3], 2]
[('B flat', 'Major'), ('A', 'Major'), [9, 2], 2]
[('A', 'Major'), ('B flat', 'Major'), [9, 2], 2]
[('B flat', 'Major'), ('B', 'Major'), [10, 3], 2]
[('B', 'Major'), ('C', 'Major'), [11, 4], 2]
[('C', 'Major'), ('F sharp', 'Major'), [11, 5], 2]
[('F sharp', 'Major'), ('G', 'Major'), [11, 6], 2]
[('F sharp', 'Major'), ('C', 'Major'), [11, 5], 2]
[('F sharp', 'Major'), ('F', 'Major'), [10, 5], 2]
[('F sharp', 'Major'), ('B flat', 'Major'), [10, 3, 5], 3]
[('F sharp', 'Major'), ('D', 'Major'), [1, 11, 6], 3]
[('F sharp', 'Major'), ('A', 'Major'), [8, 1, 11, 6], 4]
[('F sharp', 'Major'), ('E flat', 'Major'), [8, 10, 3, 5], 4]
[('F sharp', 'Major'), ('G sharp', 'Major'), [8, 1, 10, 3, 5], 5]
[('F sharp', 'Major'), ('E', 'Major'), [8, 1, 3, 6, 11], 5]
[('F sharp', 'Major'), ('C sharp', 'Major'), [1, 3, 5, 6, 8, 10], 6]
[('F sharp', 'Major'), ('B', 'Major'), [1, 3, 6, 8, 10, 11], 6]
[('C', 'Major'), ('G sharp', 'Major'), [0, 5, 7], 3]
[('G sharp', 'Major'), ('A', 'Major'), [8, 1], 2]
[('G sharp', 'Major'), ('G', 'Major'), [0, 7], 2]
[('G sharp', 'Major'), ('D', 'Major'), [1, 7], 2]
[('G sharp', 'Major'), ('C', 'Major'), [0, 5, 7], 3]
[('G sharp', 'Major'), ('E', 'Major'), [8, 1, 3], 3]
[('G sharp', 'Major'), ('B', 'Major'), [8, 1, 10, 3], 4]
[('G sharp', 'Major'), ('F', 'Major'), [0, 10, 5, 7], 4]
[('G sharp', 'Major'), ('B flat', 'Major'), [0, 10, 3, 5, 7], 5]
[('G sharp', 'Major'), ('F sharp', 'Major'), [8, 1, 10, 3, 5], 5]
[('G sharp', 'Major'), ('C sharp', 'Major'), [0, 1, 3, 5, 8, 10], 6]
[('G sharp', 'Major'), ('E flat', 'Major'), [0, 3, 5, 7, 8, 10], 6]
[('C', 'Major'), ('E', 'Major'), [9, 11, 4], 3]
[('E', 'Major'), ('B flat', 'Major'), [9, 3], 2]
[('E', 'Major'), ('E flat', 'Major'), [8, 3], 2]
[('E', 'Major'), ('F', 'Major'), [9, 4], 2]
[('E', 'Major'), ('G sharp', 'Major'), [8, 1, 3], 3]
[('E', 'Major'), ('C', 'Major'), [9, 11, 4], 3]
[('E', 'Major'), ('C sharp', 'Major'), [8, 1, 3, 6], 4]
[('E', 'Major'), ('G', 'Major'), [9, 11, 4, 6], 4]
[('E', 'Major'), ('F sharp', 'Major'), [8, 1, 3, 6, 11], 5]
[('E', 'Major'), ('D', 'Major'), [1, 11, 4, 6, 9], 5]
[('E', 'Major'), ('A', 'Major'), [1, 4, 6, 8, 9, 11], 6]
[('E', 'Major'), ('B', 'Major'), [1, 3, 4, 6, 8, 11], 6]
[('C', 'Major'), ('A', 'Major'), [9, 2, 11, 4], 4]
[('A', 'Major'), ('G sharp', 'Major'), [8, 1], 2]
[('A', 'Major'), ('E flat', 'Major'), [8, 2], 2]
[('A', 'Major'), ('C sharp', 'Major'), [8, 1, 6], 3]
[('A', 'Major'), ('F', 'Major'), [9, 2, 4], 3]
[('A', 'Major'), ('F sharp', 'Major'), [8, 1, 11, 6], 4]
[('A', 'Major'), ('C', 'Major'), [9, 2, 11, 4], 4]
[('A', 'Major'), ('B', 'Major'), [8, 1, 11, 4, 6], 5]
[('A', 'Major'), ('G', 'Major'), [9, 2, 11, 4, 6], 5]
[('A', 'Major'), ('E', 'Major'), [1, 4, 6, 8, 9, 11], 6]
[('A', 'Major'), ('D', 'Major'), [1, 2, 4, 6, 9, 11], 6]
[('C', 'Major'), ('E flat', 'Major'), [0, 2, 5, 7], 4]
[('E flat', 'Major'), ('A', 'Major'), [8, 2], 2]
[('E flat', 'Major'), ('E', 'Major'), [8, 3], 2]
[('E flat', 'Major'), ('D', 'Major'), [2, 7], 2]
[('E flat', 'Major'), ('B', 'Major'), [8, 10, 3], 3]
[('E flat', 'Major'), ('G', 'Major'), [0, 2, 7], 3]
[('E flat', 'Major'), ('F sharp', 'Major'), [8, 10, 3, 5], 4]
[('E flat', 'Major'), ('C', 'Major'), [0, 2, 5, 7], 4]
[('E flat', 'Major'), ('C sharp', 'Major'), [0, 8, 10, 3, 5], 5]
[('E flat', 'Major'), ('F', 'Major'), [0, 2, 10, 5, 7], 5]
[('E flat', 'Major'), ('B flat', 'Major'), [0, 2, 3, 5, 7, 10], 6]
[('E flat', 'Major'), ('G sharp', 'Major'), [0, 3, 5, 7, 8, 10], 6]
[('C', 'Major'), ('B flat', 'Major'), [0, 9, 2, 5, 7], 5]
[('B flat', 'Major'), ('E', 'Major'), [9, 3], 2]
[('B flat', 'Major'), ('F sharp', 'Major'), [10, 3, 5], 3]
[('B flat', 'Major'), ('D', 'Major'), [9, 2, 7], 3]
[('B flat', 'Major'), ('C sharp', 'Major'), [0, 10, 3, 5], 4]
[('B flat', 'Major'), ('G', 'Major'), [0, 9, 2, 7], 4]
[('B flat', 'Major'), ('G sharp', 'Major'), [0, 10, 3, 5, 7], 5]
[('B flat', 'Major'), ('C', 'Major'), [0, 9, 2, 5, 7], 5]
[('B flat', 'Major'), ('E flat', 'Major'), [0, 2, 3, 5, 7, 10], 6]
[('B flat', 'Major'), ('F', 'Major'), [0, 2, 5, 7, 9, 10], 6]
[('C', 'Major'), ('D', 'Major'), [9, 2, 11, 4, 7], 5]
[('D', 'Major'), ('C sharp', 'Major'), [1, 6], 2]
[('D', 'Major'), ('G sharp', 'Major'), [1, 7], 2]
[('D', 'Major'), ('E flat', 'Major'), [2, 7], 2]
[('D', 'Major'), ('B flat', 'Major'), [9, 2, 7], 3]
[('D', 'Major'), ('F sharp', 'Major'), [1, 11, 6], 3]
[('D', 'Major'), ('B', 'Major'), [1, 11, 4, 6], 4]
[('D', 'Major'), ('F', 'Major'), [9, 2, 4, 7], 4]
[('D', 'Major'), ('C', 'Major'), [9, 2, 11, 4, 7], 5]
[('D', 'Major'), ('E', 'Major'), [1, 11, 4, 6, 9], 5]
[('D', 'Major'), ('A', 'Major'), [1, 2, 4, 6, 9, 11], 6]
[('D', 'Major'), ('G', 'Major'), [2, 4, 6, 7, 9, 11], 6]
[('C', 'Major'), ('G', 'Major'), [0, 2, 4, 7, 9, 11], 6]
[('G', 'Major'), ('G sharp', 'Major'), [0, 7], 2]
[('G', 'Major'), ('F sharp', 'Major'), [11, 6], 2]
[('G', 'Major'), ('B', 'Major'), [11, 4, 6], 3]
[('G', 'Major'), ('E flat', 'Major'), [0, 2, 7], 3]
[('G', 'Major'), ('B flat', 'Major'), [0, 9, 2, 7], 4]
[('G', 'Major'), ('E', 'Major'), [9, 11, 4, 6], 4]
[('G', 'Major'), ('A', 'Major'), [9, 2, 11, 4, 6], 5]
[('G', 'Major'), ('F', 'Major'), [0, 9, 2, 4, 7], 5]
[('G', 'Major'), ('C', 'Major'), [0, 2, 4, 7, 9, 11], 6]
[('G', 'Major'), ('D', 'Major'), [2, 4, 6, 7, 9, 11], 6]
[('C', 'Major'), ('F', 'Major'), [0, 2, 4, 5, 7, 9], 6]
[('F', 'Major'), ('B', 'Major'), [10, 4], 2]
[('F', 'Major'), ('F sharp', 'Major'), [10, 5], 2]
[('F', 'Major'), ('E', 'Major'), [9, 4], 2]
[('F', 'Major'), ('A', 'Major'), [9, 2, 4], 3]
[('F', 'Major'), ('C sharp', 'Major'), [0, 10, 5], 3]
[('F', 'Major'), ('G sharp', 'Major'), [0, 10, 5, 7], 4]
[('F', 'Major'), ('D', 'Major'), [9, 2, 4, 7], 4]
[('F', 'Major'), ('G', 'Major'), [0, 9, 2, 4, 7], 5]
[('F', 'Major'), ('E flat', 'Major'), [0, 2, 10, 5, 7], 5]
[('F', 'Major'), ('B flat', 'Major'), [0, 2, 5, 7, 9, 10], 6]
[('F', 'Major'), ('C', 'Major'), [0, 2, 4, 5, 7, 9], 6]
[('B', 'Major'), ('F', 'Major'), [10, 4], 2]
[('B', 'Major'), ('G', 'Major'), [11, 4, 6], 3]
[('B', 'Major'), ('E flat', 'Major'), [8, 10, 3], 3]
[('B', 'Major'), ('G sharp', 'Major'), [8, 1, 10, 3], 4]
[('B', 'Major'), ('D', 'Major'), [1, 11, 4, 6], 4]
[('B', 'Major'), ('A', 'Major'), [8, 1, 11, 4, 6], 5]
[('B', 'Major'), ('C sharp', 'Major'), [8, 1, 10, 3, 6], 5]
[('C sharp', 'Major'), ('D', 'Major'), [1, 6], 2]
[('C sharp', 'Major'), ('A', 'Major'), [8, 1, 6], 3]
[('C sharp', 'Major'), ('F', 'Major'), [0, 10, 5], 3]
[('C sharp', 'Major'), ('B flat', 'Major'), [0, 10, 3, 5], 4]
[('C sharp', 'Major'), ('E', 'Major'), [8, 1, 3, 6], 4]
[('C sharp', 'Major'), ('B', 'Major'), [8, 1, 10, 3, 6], 5]
[('B', 'Major'), ('F sharp', 'Major'), [1, 3, 6, 8, 10, 11], 6]
[('B', 'Major'), ('E', 'Major'), [1, 3, 4, 6, 8, 11], 6]
[('C sharp', 'Major'), ('E flat', 'Major'), [0, 8, 10, 3, 5], 5]
[('C sharp', 'Major'), ('G sharp', 'Major'), [0, 1, 3, 5, 8, 10], 6]
[('C sharp', 'Major'), ('F sharp', 'Major'), [1, 3, 5, 6, 8, 10], 6]
